### ISSUE TITLE
Release grpc-spring-boot-starter with latest grpcVersion = '1.45.1'

### ISSUE THREAD

**Issue by arvgord** [yidongnan/grpc-spring-boot-starter#655]
@yidongnan Could you release grpc-spring-boot-starter with grpcVersion = '1.45.1' please?

**Comment by ST-DDT** [comment]
We can, is there a specific reason for that?

**Comment by arvgord** [comment]
I get java.lang.NoClassDefFoundError: io/grpc/ClientStreamTracer$InternalLimitedInfoFactory with grpcVersion 1.42.2 when my app works with another app with grpcVersion 1.45.1

**Comment by ST-DDT** [comment]
Do you use the grpc bom to ensure all grpc dependencies use the same version?
The class not found exception is usually an indicator for grpc version conflicts.

**Comment by Volodymyr-Maiboroda-Imprivata** [comment]
We will migrate to a 1.44 or higher version in our project. We would like to know if the spring-grpc is going to update grpc dependencies and when the new release will be provided

**Comment by ST-DDT** [comment]
I hope that I find some time this weekend to push the remaining features for the next release.

**Comment by ST-DDT** [comment]
Well, it looks like I need some more time for the release.
I would liek to tackle at least the issues marked with bug in the list: https://github.com/yidongnan/grpc-spring-boot-starter/milestone/17

**Comment by ST-DDT** [comment]
Fixed in latest release.
